version: "3"
services:
  satisfactory:
    image: ghcr.io/ekman/satisfactory:1
    build:
      context: .
    restart: unless-stopped
    volumes:
      - "./config:/home/steam/.config/Epic/FactoryGame/Saved/SaveGames"
      - "./game:/home/steam/game"
    expose:
      - 15777:15777/udp
      - 15000:15000/udp
      - 7777:7777/udp

